apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-grand-moff-com-tls
spec:
  secretName: k8s-grand-moff-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.grand-moff.com
  dnsNames:
    - k8s.grand-moff.com
    - k8s2.grand-moff.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.grand-moff.com
          - k8s2.grand-moff.com